fix issue with jobs

diff --git a/templates/1-variables.yml b/templates/1-variables.yml
--- a/templates/1-variables.yml
+++ b/templates/1-variables.yml
@@ -22,6 +22,7 @@ stages:
   - group: lookup-variables
   - name: staticVar
     value: 'static value'
+  
   # Value based on the template parameter.
   - name: compileVar
     ${{ if eq(parameters.boolVar, true) }}: 
@@ -33,9 +34,11 @@ stages:
   - name: overwriteVar
     value: 'stage level'
 
-# Best practices:
-# - Use a nameing convention: example snakeCase.
-# - Use a group for all variables that are used in multiple pipelines.
+# Best practices: variables
+# - Use (and enforce) a naming convention: example snakeCase.
+# - Use template variables for shared variables that are used in multiple pipelines in the same repo, containing no secrets.
+# - Use group variables for shared variables that are used in multiple pipelines in multiple repo's, may contain secret values.
+# - Prefere serviceConnections over group variables for secrets to access external services.
 
   jobs:
   - job: j1
@@ -237,63 +240,64 @@ stages:
   - job: j1
     displayName: Get Variables (s1a.j3)
     steps:
-      - checkout: none  # skip checkout
-      - script: |
-          echo "job_variable: $(job_variable) (replaced in compile time)"
-          echo "job_variable: $JOB_VARIABLE   (through environment)"
-          echo "deployment_var: $(deployment_var) (replaced in compile time)"
-          echo "deployment_var: $DEPLOYMENT_VAR   (through environment)"
-        displayName: Show vars (future stage)
+    - checkout: none  # skip checkout
+    - script: |
+        echo "job_variable: $(job_variable) (replaced in compile time)"
+        echo "job_variable: $JOB_VARIABLE   (through environment)"
+        echo "deployment_var: $(deployment_var) (replaced in compile time)"
+        echo "deployment_var: $DEPLOYMENT_VAR   (through environment)"
+      displayName: Show vars (future stage)
 
 
 - stage: s2
   displayName: Practicle Examples (s2)
 
-  job: j1
-  displayName: Unique Artifacts
-  # Tip: create unique artifact names, this allow jobs to be restartable.
-  #
-  # Creating an artifact with the same name will fail the pipeline.
-  # This is a problem when you have a pipeline with multiple jobs and one of them fails.
-  # The pipeline will fail and you cannot restart the pipeline, because the artifact already exists.
+  jobs:
+  - job: j1
+    displayName: Unique Artifacts
+    # Tip: create unique artifact names, this allow jobs to be restartable.
+    #
+    # Creating an artifact with the same name will fail the pipeline.
+    # This is a problem when you have a pipeline with multiple jobs and one of them fails.
+    # The pipeline will fail and you cannot restart the pipeline, because the artifact already exists.
 
-  retries: 1  # On purpose: restart after first failure in last step.
+    retries: 1  # On purpose: restart after first failure in last step.
 
-  steps:
-  - checkout: none  # skip checkout
+    steps:
+    - checkout: none  # skip checkout
 
-  # Demonstrate failing artifact creation:
-  - publish: $(Build.ArtifactStagingDirectory)
-    artifact: mustbe_unique
-    displayName: Artifact
-    continueOnError: true
+    # Demonstrate failing artifact creation:
+    - publish: $(Build.ArtifactStagingDirectory)
+      artifact: mustbe_unique
+      displayName: Artifact
+      continueOnError: true
 
-  - publish: $(Build.ArtifactStagingDirectory)
-    artifact: mustbe_unique
-    displayName: Artifact_fail
-    continueOnError: true
+    - publish: $(Build.ArtifactStagingDirectory)
+      artifact: mustbe_unique
+      displayName: Artifact_fail
+      continueOnError: true
 
-  # Solution: predefine a unique name for the artifact.
-  # After Job-restart a new artifact will be created.
-  - bash: |
-      echo "Create artifact name based on the buildId or system.jobattempt"
-      echo "  Build.BuildId: $(Build.BuildId)"
-      echo "  System.JobAttempt: $(system.jobattempt)"
-      
-      name="artifact-$(Build.BuildId)#$(system.jobattempt)"
-      echo "  name: $name"
-      echo "##vso[task.setvariable variable=name;isOutput=true]$name"
-    displayName: Show vars (future stage)
-    name: artifact
+    # Solution: predefine a unique name for the artifact.
+    # After Job-restart a new artifact will be created.
+    - bash: |
+        echo "Create artifact name based on the buildId or system.jobattempt"
+        echo "  Build.BuildId: $(Build.BuildId)"
+        echo "  System.JobAttempt: $(system.jobattempt)"
+        
+        name="artifact-$(Build.BuildId)#$(system.jobattempt)"
+        echo "  name: $name"
+        echo "##vso[task.setvariable variable=name;isOutput=true]$name"
+      displayName: Show vars (future stage)
+      name: artifact
 
-  # Variable defiend with isOutput=true, therefor referencing must be prefixed with the task name.
-  - publish: $(Build.ArtifactStagingDirectory)
-    artifact: $(artifact.name)
-    displayName: Artifact_unique
+    # Variable defiend with isOutput=true, therefor referencing must be prefixed with the task name.
+    - publish: $(Build.ArtifactStagingDirectory)
+      artifact: $(artifact.name)
+      displayName: Artifact_unique
 
-  - bash: |
-      [ $(system.jobattempt) -eq 0 ] && exit 1
+    - bash: |
+        [ $(system.jobattempt) -eq 0 ] && exit 1
 
-      echo "After second try, no failure..."
-      echo "Later stages and jobs can link to the artifact name using the variable reference: s2.j1.artifact.name"
-    displayName: Fail on first attempt
+        echo "After second try, no failure..."
+        echo "Later stages and jobs can link to the artifact name using the variable reference: s2.j1.artifact.name"
+      displayName: Fail on first attempt
